In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("C:\\Users\PRASHANT\\Documents\\datasets wscube tech\\house price predictions\\data.csv")
dataset.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [3]:
dataset.tail()

date          price  bedrooms  bathrooms  sqft_living  \
4595  2014-07-09 00:00:00  308166.666667       3.0       1.75         1510   
4596  2014-07-09 00:00:00  534333.333333       3.0       2.50         1460   
4597  2014-07-09 00:00:00  416904.166667       3.0       2.50         3010   
4598  2014-07-10 00:00:00  203400.000000       4.0       2.00         2090   
4599  2014-07-10 00:00:00  220600.000000       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated             street       city  \
4595              0      1954          1979     501 N 143rd St    Seattle   
4596              0      1983          2009   14855 SE 10th Pl   Bellevue   
4597              0      2009             0   759 Ilwaco Pl NE     Renton   
4598           1020      1974             0  5148 S Creston St    Seattle   
4599              0      1990             0  18717 SE 258th St  Covington   

      statezip country  
4595  WA 98133     USA  
4596  WA 98007     USA  
4597  WA 98059     USA  
4598  WA 98178     USA  
4599  WA 98042     USA

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           4600 non-null   object 
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64  
 5   sqft_lot       4600 non-null   int64  
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64  
 8   view           4600 non-null   int64  
 9   condition      4600 non-null   int64  
 10  sqft_above     4600 non-null   int64  
 11  sqft_basement  4600 non-null   int64  
 12  yr_built       4600 non-null   int64  
 13  yr_renovated   4600 non-null   int64  
 14  street         4600 non-null   object 
 15  city           4600 non-null   object 
 16  statezip       4600 non-null   object 
 17  country        4600 non-null   object 
dtypes: float

In [5]:
dataset.describe()

price     bedrooms    bathrooms   sqft_living      sqft_lot  \
count  4.600000e+03  4600.000000  4600.000000   4600.000000  4.600000e+03   
mean   5.519630e+05     3.400870     2.160815   2139.346957  1.485252e+04   
std    5.638347e+05     0.908848     0.783781    963.206916  3.588444e+04   
min    0.000000e+00     0.000000     0.000000    370.000000  6.380000e+02   
25%    3.228750e+05     3.000000     1.750000   1460.000000  5.000750e+03   
50%    4.609435e+05     3.000000     2.250000   1980.000000  7.683000e+03   
75%    6.549625e+05     4.000000     2.500000   2620.000000  1.100125e+04   
max    2.659000e+07     9.000000     8.000000  13540.000000  1.074218e+06   

            floors   waterfront         view    condition   sqft_above  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      1.512065     0.007174     0.240652     3.451739  1827.265435   
std       0.538288     0.084404     0.778405     0.677230   862.168977   
min       1.000000     0.000000     0.000000     1.000000   370.000000   
25%       1.000000     0.000000     0.000000     3.000000  1190.000000   
50%       1.500000     0.000000     0.000000     3.000000  1590.000000   
75%       2.000000     0.000000     0.000000     4.000000  2300.000000   
max       3.500000     1.000000     4.000000     5.000000  9410.000000   

       sqft_basement     yr_built  yr_renovated  
count    4600.000000  4600.000000   4600.000000  
mean      312.081522  1970.786304    808.608261  
std       464.137228    29.731848    979.414536  
min         0.000000  1900.000000      0.000000  
25%         0.000000  1951.000000      0.000000  
50%         0.000000  1976.000000      0.000000  
75%       610.000000  1997.000000   1999.000000  
max      4820.000000  2014.000000   2014.000000

In [6]:
dataset.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [7]:
dataset.drop(columns=['date','yr_built','yr_renovated','street','city','statezip','country'],inplace=True)

In [8]:
dataset.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  
0     0          3        1340              0  
1     4          5        3370            280  
2     0          4        1930              0  
3     0          4        1000           1000  
4     0          4        1140            800

In [9]:
dataset.select_dtypes(include=["object","bool"]).columns

Index([], dtype='object')

In [10]:
dataset.isnull().sum()

price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
dtype: int64

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   price          4600 non-null   float64
 1   bedrooms       4600 non-null   float64
 2   bathrooms      4600 non-null   float64
 3   sqft_living    4600 non-null   int64  
 4   sqft_lot       4600 non-null   int64  
 5   floors         4600 non-null   float64
 6   waterfront     4600 non-null   int64  
 7   view           4600 non-null   int64  
 8   condition      4600 non-null   int64  
 9   sqft_above     4600 non-null   int64  
 10  sqft_basement  4600 non-null   int64  
dtypes: float64(4), int64(7)
memory usage: 395.4 KB


# Scaling

In [13]:
from sklearn.preprocessing import StandardScaler

In [12]:
input_data = dataset.iloc[:,1:]
output_data = dataset["price"]

In [14]:
st = StandardScaler()
input_data = pd.DataFrame(st.fit_transform(input_data),columns=input_data.columns)

In [15]:
input_data

bedrooms  bathrooms  sqft_living  sqft_lot    floors  waterfront  \
0    -0.441122  -0.843204    -0.829971 -0.193434 -0.022416   -0.085004   
1     1.759705   0.432802     1.568528 -0.161718  0.906555   -0.085004   
2    -0.441122  -0.205201    -0.217367 -0.080978 -0.951388   -0.085004   
3    -0.441122   0.113800    -0.144686 -0.190145 -0.951388   -0.085004   
4     0.659291   0.432802    -0.206984 -0.121306 -0.951388   -0.085004   
...        ...        ...          ...       ...       ...         ...   
4595 -0.441122  -0.524202    -0.653458 -0.236689 -0.951388   -0.085004   
4596 -0.441122   0.432802    -0.705374 -0.202882  0.906555   -0.085004   
4597 -0.441122   0.432802     0.904009 -0.218462  0.906555   -0.085004   
4598  0.659291  -0.205201    -0.051238 -0.229164 -0.951388   -0.085004   
4599 -0.441122   0.432802    -0.674224 -0.188139  0.906555   -0.085004   

          view  condition  sqft_above  sqft_basement  
0    -0.309194  -0.667112   -0.565224      -0.672464  
1     4.830079   2.286416    1.789559      -0.069128  
2    -0.309194   0.809652    0.119171      -0.672464  
3    -0.309194   0.809652   -0.959621       1.482306  
4    -0.309194   0.809652   -0.797222       1.051352  
...        ...        ...         ...            ...  
4595 -0.309194   0.809652   -0.368025      -0.672464  
4596 -0.309194  -0.667112   -0.426025      -0.672464  
4597 -0.309194  -0.667112    1.371962      -0.672464  
4598 -0.309194  -0.667112   -0.878421       1.525401  
4599 -0.309194   0.809652   -0.391225      -0.672464  

[4600 rows x 10 columns]

# Train-Test-Split

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(input_data,output_data,test_size=0.2,random_state=42)

In [ ]:
# 

In [17]:
from sklearn.neighbors import KNeighborsRegressor

In [18]:
knn = KNeighborsRegressor(n_neighbors=5)

In [19]:
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [21]:
knn.predict(x_test)

array([ 445190.       ,  336690.       , 1122200.       ,  675960.       ,
        364054.       ,  513000.       ,  364800.       ,  414290.       ,
        455385.4      ,  466625.4      ,  570001.       ,  442800.       ,
        909680.       ,  209600.       ,  391990.       , 1351000.       ,
        524585.       ,  592800.       ,  940800.       ,  818842.5      ,
        893700.       ,  637032.2      ,  515400.       ,  421345.5714286,
        275789.       ,  281660.       ,  635990.       ,  733790.       ,
        385860.       ,  729100.       , 1778000.       ,  415610.       ,
        952196.2      ,  396977.6      ,  292623.4      ,  386090.       ,
        849000.       ,  892600.       ,  303600.       ,  432756.       ,
        329990.       ,  399400.       ,  431880.       ,  450950.       ,
        315000.       ,  431140.       ,  501900.       ,  584000.       ,
        650790.       ,  669400.       , 1299499.4      ,  564290.       ,
        433450.       ,  

In [22]:
knn.score(x_test,y_test),knn.score(x_train,y_train)

(0.027563214176156814, 0.6432106239442187)

In [26]:
knn.predict(x_test)

array([ 445190.       ,  336690.       , 1122200.       ,  675960.       ,
        364054.       ,  513000.       ,  364800.       ,  414290.       ,
        455385.4      ,  466625.4      ,  570001.       ,  442800.       ,
        909680.       ,  209600.       ,  391990.       , 1351000.       ,
        524585.       ,  592800.       ,  940800.       ,  818842.5      ,
        893700.       ,  637032.2      ,  515400.       ,  421345.5714286,
        275789.       ,  281660.       ,  635990.       ,  733790.       ,
        385860.       ,  729100.       , 1778000.       ,  415610.       ,
        952196.2      ,  396977.6      ,  292623.4      ,  386090.       ,
        849000.       ,  892600.       ,  303600.       ,  432756.       ,
        329990.       ,  399400.       ,  431880.       ,  450950.       ,
        315000.       ,  431140.       ,  501900.       ,  584000.       ,
        650790.       ,  669400.       , 1299499.4      ,  564290.       ,
        433450.       ,  

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
lr = LinearRegression()

In [30]:
lr.fit(x_train,y_train)

LinearRegression()

In [31]:
lr.score(x_test,y_test),lr.score(x_train,y_train)

(0.03172583406158158, 0.5173770162868334)

In [32]:
lr.predict(x_test)

array([ 362431.65837901,  414916.47785049, 1037223.95965121,
        637626.52975878,  393359.46247841,  677246.52016068,
        519685.03759109,  473881.09753544,  525024.58258295,
        533467.38087558,  734494.01248257,  347492.47851919,
        821344.93140323,  521008.01350126,  397833.59917008,
        737234.14575087,  576741.21806571,  522548.44930302,
       1110191.67948973,  891089.2543058 , 1402004.66250014,
        649868.47765952,  643474.73402628,  505186.33905508,
        248009.81024367,  244056.88970988,  678338.78271701,
        880759.21016663,  339035.87905805,  875377.33832767,
       1708297.77308822,  423479.80325285, 1147794.94032491,
        468218.5786776 ,  215405.11956923,  394419.12218713,
        829363.14886874,  770570.9637647 ,  304161.30008713,
        588589.12073053,  413009.0058602 ,  324506.68699877,
        416588.4293522 ,  408962.70731548,  315200.6654183 ,
        273853.13171076,  503975.05452055,  538794.07100923,
        814983.15923642,